name: qr_code_generator
description: A Flutter app to generate & scan QR codes for URLs and WiFi credentials.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  emojis: ^0.9.9
  flutter:
    sdk: flutter
  google_mlkit_barcode_scanning: ^0.12.0
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  mobile_scanner: ^5.1.1
  path_provider: ^2.1.4
  provider: ^6.1.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.0
  wifi_iot: ^0.3.19

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependencies_override:
  win32: ^3.1.4

flutter:
  uses-material-design: true
