name: qr_code_generator
description: A Flutter app to generate QR codes for URLs and WiFi credentials.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  qr_code_scanner: ^1.0.1
  qr_code_tools: ^0.1.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
